/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R18A_Group7_Asm2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Timer timer = Timer.getInstance();
        OwnerSummary ownerSummary = OwnerSummary.getInstance();

        VendingMachine.main(new String[]{});
        timer.setCurrentFrame("vend");
    }
}
