/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendorMachine;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {

    }

    @Test
    public void getGreeting() {
        App app = new App();
        assertEquals(app.getGreeting(), "Hello world.");
    }

    @Test
    public void main() {
        try {
            App.main(null);
        } catch (Exception e1){
            fail(e1.getStackTrace()+"");

        }
    }
}
